language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --coverage-text
